# seeds.py - Initial data for seeding the database

REMEDY_SEEDS = [
(" Yawning","Kali Phos (Potassium Phosphoricum)"),
(" Yellow coating at the back of the tongue","Nat Phos (Sodium Phosphate)"),
(" Yellow coating on the tongue","Nat Sulph (Sodium Sulphate)"),
(" Yellow coating on the tongue Yellow slimy tongue","Kali Sulph (Potassium Sulphate)"),
(" yellow dandruff","Kali Sulph (Potassium Sulphate)"),
(" Yellow Diarrhea","Kali Sulph (Potassium Sulphate)"),
(" yellow discharge coming out of the ear","Kali Sulph (Potassium Sulphate)"),
(" Yellow discharges A good residual remedy for children with bronchitis","Kali Sulph (Potassium Sulphate)"),
(" Yellow green sinusitis","Nat Sulph (Sodium Sulphate)"),
(" Yellow thick pus","Calc Sulph (Calcium Sulphate)"),
(" You can build people up with this remedy","Calc Phos (Calcium Phosphate)"),
(" Back Problems: Calc Flor has and affinity for the lower back","Calc Flor (Calcium Floride) "),
(" Bone Spurs (Hekla Lava)","Calc Flor (Calcium Floride) "),
(" Bumps or bony growths","Calc Flor (Calcium Floride) "),
(" Carpal Tunnel Syndrome","Calc Flor (Calcium Floride) "),
(" degeneration of the vertebrae","Calc Flor (Calcium Floride) "),
(" Disc problems","Calc Flor (Calcium Floride) "),
(" Elastic tissue – too much or too little","Calc Flor (Calcium Floride) "),
(" Ganglion cysts","Calc Flor (Calcium Floride) "),
(" heat & brimstone - Earth & Fire Commonly known as gypsum or plaster of paris",""),
(" herniated discs that keeps re herniating","Calc Flor (Calcium Floride) "),
(" Injury of the wrist – it’s too loose","Calc Flor (Calcium Floride) "),
(" Joints slip out of sockets easily – gentle continual pressure with the palm of the hand can pop a joint back in","Calc Flor (Calcium Floride) "),
(" Joints: The #1cell salt remedy for ","Calc Flor (Calcium Floride) "),
(" slipped disc","Calc Flor (Calcium Floride) "),
(" Teeth: Strengthens the tooth enamel so it is helpful for children who get cavities easily","Calc Flor (Calcium Floride) "),
(" Tendons and Ligaments: It’s a good remedy for people who can’t hold adjustments after chiropractic treatment","Calc Flor (Calcium Floride) "),
(" Tendons that contract or you get tumors on the tendon","Calc Flor (Calcium Floride) "),
(" Total personality change after a mild or severe concussion","Nat Sulph (Sodium Sulphate)"),
(" trauma to the joints","Calc Flor (Calcium Floride) "),
(" Cough coming with mucus "," Nat Mur (Natrum Muriaticum)"),
(" Cough coming again and again "," Nat Mur (Natrum Muriaticum), Ferrum Phos (Ferrum Phosphoricum), Mag Phos (Magnesium Phosphate), Kali Mur (Potassium Muriaticum), Kali Phos (Potassium Phosphate)"),
(" Pain-related "," Ferrum Phos (Ferrum Phosphoricum)"),
(" Cough due to fever ","Calc Sulph (Calcium Sulfate)"),
(" Old cough in cancer patients "," Calc Phos (Calcium Phosphate), Silicae, Nat Mur (Natrum Muriaticum)"),
(" Pain in the left side of the abdomen while coughing "," Kali Phos (Potassium Phosphate)"),
(" Tears flow from the eyes while coughing "," Nat Mur (Natrum Muriaticum)"),
(" Chest pain while coughing "," Nat Mur (Natrum Muriaticum), Ferrum Phos (Ferrum Phosphoricum)"),
(" Feeling of tightness in the chest while coughing "," Silicae"),
(" Cough with Night sweats "," Silicae"),
(" Cough becomes lighter "," Ferrum Phos (Ferrum Phosphoricum), Nat Mur (Natrum Muriaticum)"),
(" Scratching behind the breastbone and cough due to it "," Nat Mur (Natrum Muriaticum), Kali Mur (Potassium Muriaticum)"),
(" Scratching in the throat "," Calc Flor (Calcium Floride)"),
(" Scratching at night "," Calc Flor (Calcium Floride)"),
(" Scratching in the respiratory tract "," Ferrum Phos (Ferrum Phosphoricum), Kali Phos (Potassium Phosphate), Silicae"),
(" Cough coming on its own "," Mag Phos (Magnesium Phosphate), Calc Flor (Calcium Floride), Silicae"),
("Cough with Tongue sticking out and stretching "," Calc Flor (Calcium Floride)"),
(" Cough when While lying down "," Nat Mur (Natrum Muriaticum)"),
(" Cough - More in warm room "," Kali Phos (Potassium Phosphate)"),
(" Cough - More in the morning "," Kali Phos (Potassium Phosphate)"),
(" Cough - More in the evening ","Kali Mur (Potassium Muriaticum)"),
(" Feels good coughing on its own "," Calc Phos (Calcium Phosphate)"),
(" Feels good after coughing "," Calc Phos (Calcium Phosphate)"),
(" Feels good in open air "," Kali Phos (Potassium Phosphate)"),
(" Cough - Need open air to feel better "," Kali Phos (Potassium Phosphate)"),
(" Dry cough, shaking from the inside "," Ferrum Phos (Ferrum Phosphoricum), Nat Mur (Natrum Muriaticum)"),
(" Mucus discharge while coughing "," Nat Mur (Natrum Muriaticum)"),
(" Nausea while coughing and vomiting after "," Nat Mur (Natrum Muriaticum)"),
(" Cough - Due to air in the room, swallowing something, physical exertion, walking, eating sour food, internal heat "," Nat Mur (Natrum Muriaticum)"),
(" Cough - Due to drinking hot drinks "," Nat Mur (Natrum Muriaticum)"),
(" Cough - Coming at night due to itching "," Kali Phos (Potassium Phosphate)"),
(" Cough - Severe, mild, and recurring "," Ferrum Phos (Ferrum Phosphoricum), Kali Mur (Potassium Muriaticum) "),
(" Old cough in patients whose hands and feet always get cold "," Calc Phos (Calcium Phosphate)"),
(" Cough caused by bending the neck and touching the throat (glands) "," Ferrum Phos (Ferrum Phosphoricum)"),
(" Cough - While sitting straight "," Nat Mur (Natrum Muriaticum)"),
(" Forceful cough with running nose "," Kali Mur (Potassium Muriaticum)"),
]