# seeds.py - Initial data for seeding the database

REMEDY_SEEDS = [
("Allergic to the Sun","Nat Mur (Natrum Muriaticum)"),
("Aristocratic child – refined Frail asthmatic child","Silica (Silica)"),
("Bone marrow transplants Anemia after radiation","Ferrum Phos (Ferrum Phosphoricum)"),
("Hard to please children Capricious state – dissatisfaction","Calc Phos (Calcium Phosphate)"),
("Homeopathic Valium taken to gently calm a person down who is nervous or stressed","Kali Phos (Potassium Phosphoricum)"),
("Knotty Gland – knotty lymphatic glands","Calc Flor (Calcium Floride) "),
("Perfectionist – They tear up paper because it isn’t perfect when drawing or doing a homework assignment","Calc Phos (Calcium Phosphate)"),
("coughing up globs of yellow mucous","Kali Sulph (Potassium Sulphate)"),
(" 2 years old and since the fever they haven’t grown","Calc Phos (Calcium Phosphate)"),
("Redness","Ferrum Phos (Ferrum Phosphoricum)"),
("Swelling","Ferrum Phos (Ferrum Phosphoricum)"),
("stiffness in joint","Calc Flor (Calcium Floride) "),
("First aid and trauma remedy","Ferrum Phos (Ferrum Phosphoricum)"),
("high strung nervous type of person","Kali Phos (Potassium Phosphoricum)"),
(" A great nutritional tonic","Calc Phos (Calcium Phosphate)"),
("Fears of rejection","Nat Mur (Natrum Muriaticum)"),
("Insomnia","Kali Phos (Potassium Phosphoricum)"),
(" A rusty hinge remedy (Rhus Tox)","Calc Flor (Calcium Floride) "),
(" a sprained ankle with no swelling and no modalities","Ferrum Phos (Ferrum Phosphoricum)"),
(" A very good remedy for Children","Calc Phos (Calcium Phosphate)"),
(" abscess","Calc Sulph (Calcium Sulphate)"),
(" abscesses form easily One of the best remedies for keloid scars","Silica (Silica)"),
(" Acidity: Nat Phos people are very sensitive to acid foods","Nat Phos (Sodium Phosphate)"),
(" Acne remedy","Calc Sulph (Calcium Sulphate)"),
(" Acne with a lot of pus","Silica (Silica)"),
(" Acute and chronic Hepatitis","Nat Sulph (Sodium Sulphate)"),
(" Adults can moan and groan and complain","Calc Phos (Calcium Phosphate)"),
(" Affects nutrition of the bones and teeth","Calc Phos (Calcium Phosphate)"),
(" Affects respiratory mucous membranes and skin where it causes desquamation","Kali Sulph (Potassium Sulphate)"),
(" Agaricus) TMJ problems Menstrual Cramps – 30X Mag Phos – Every time she got cramps she used 30X Mag Phos","Mag Phos (Magnesium Phosphate)"),
(" Aggravated by the full moon- the worms are hatching Grinding of the teeth","Nat Phos (Sodium Phosphate)"),
(" alcohol induced bladder infections from drinking alcoholic beverages","Nat Phos (Sodium Phosphate)"),
(" Alkaline is life giving- High acid; acid foods","Nat Phos (Sodium Phosphate)"),
(" All acutes and first aid","Ferrum Phos (Ferrum Phosphoricum)"),
(" All kinds of sore throats especially inflammatory","Ferrum Phos (Ferrum Phosphoricum)"),
(" All songs about lost love on the radio are Nat Mur","Nat Mur (Natrum Muriaticum)"),
(" all week worried about putting out the effort to get it done","Silica (Silica)"),
(" also boils","Silica (Silica)"),
(" also greasy skin","Nat Mur (Natrum Muriaticum)"),
(" also it is helpful for sensitive teeth","Calc Flor (Calcium Floride) "),
(" also the elastic and connective tissue of the body","Calc Flor (Calcium Floride) "),
(" Always feels best in warm dry air","Nat Sulph (Sodium Sulphate)"),
(" Alzheimer’s (Anacardium for complete loss of memory also Alumina) Early stages of MS it may help stabilize nerve sheaths Depression without a cause (any remedy without a cause use tissue salts)(Natrum Carb – depressed about the state of the world) Indisposed to meet people or talk with them","Kali Phos (Potassium Phosphoricum)"),
(" An acid / alkaline balancer","Nat Phos (Sodium Phosphate)"),
(" Anal fissures ","Silica (Silica)"),
("removing foreign objects from the body","Silica (Silica)"),
(" and a heavy flooding period","Ferrum Phos (Ferrum Phosphoricum)"),
(" and accountants’ i","Kali Phos (Potassium Phosphoricum)"),
(" and exostosis","Calc Flor (Calcium Floride) "),
(" and flu’s","Ferrum Phos (Ferrum Phosphoricum)"),
(" and sweaty palms","Calc Phos (Calcium Phosphate)"),
(" angry","Calc Phos (Calcium Phosphate)"),
(" Ankle problems with tendons and ligament weaknesses","Calc Flor (Calcium Floride) "),
(" apnea","Kali Sulph (Potassium Sulphate)"),
(" are industrious and can withstand a lot of pressure","Calc Flor (Calcium Floride) "),
(" Arsenicum Album for children with leukemia) People coming out of the hospital Anemia from loss of blood","Ferrum Phos (Ferrum Phosphoricum)"),
(" arthritic nosodites on the hands and fingers","Calc Flor (Calcium Floride) "),
(" Arthritis < (worse) dampness < 4 to 5 AM especially asthma attacks or diarrheas Inflammation around the root of the nails","Nat Sulph (Sodium Sulphate)"),
(" Asthma after head injury","Nat Sulph (Sodium Sulphate)"),
(" Asthma in children","Nat Sulph (Sodium Sulphate)"),
(" August Dog Days of summer","Nat Sulph (Sodium Sulphate)"),
(" Aunt Sue – never re married after 20 yrs","Nat Mur (Natrum Muriaticum)"),
(" Back injuries  Pulled Back Whiplash remedy – The neck cramps up (Bryonia","Mag Phos (Magnesium Phosphate)"),
(" Back: Stiffness of the spine","Nat Sulph (Sodium Sulphate)"),
(" Bashful stool – stool comes out and goes back in","Silica (Silica)"),
(" be allergic to it or reject milk","Calc Phos (Calcium Phosphate)"),
(" because of their concerns about running out of energy","Silica (Silica)"),
(" better lying on something hard or pressing against the fist or ans object such as a book","Nat Mur (Natrum Muriaticum)"),
(" Big Thirst","Nat Phos (Sodium Phosphate)"),
(" Big Urination","Nat Phos (Sodium Phosphate)"),
(" bile flow problems in the liver and gallbladder","Nat Sulph (Sodium Sulphate)"),
(" Bleeding from fibroids","Ferrum Phos (Ferrum Phosphoricum)"),
(" blinding headache","Nat Mur (Natrum Muriaticum)"),
(" Blindness from head injury","Nat Sulph (Sodium Sulphate)"),
(" Blisters on the tip of the tongue","Nat Phos (Sodium Phosphate)"),
(" Blocked Eustachian tubes – hearing","Kali Mur (Potassium Muriaticum) "),
(" Blood Sugar: A good remedy for Diabetes #1 Cell salt for Diabetes (Phosphorus is the main homeopathic remedy) It may help lower the dose needed by 5 to10 units of insulin","Nat Phos (Sodium Phosphate)"),
(" Blood: Biggest remedy in homeopathy for ANEMIA","Ferrum Phos (Ferrum Phosphoricum)"),
(" boils","Calc Sulph (Calcium Sulphate)"),
(" Boils in the ears (Calcarea Picrata painful boils in the ears) Gum Boils Diarrhea can have the smell of rotten eggs (sulfur like) ","Calc Sulph (Calcium Sulphate)"),
(" bone cancer –it has been used for the metastasis","Calc Flor (Calcium Floride) "),
(" bone curvatures including spinal – Calc Flor","Calc Phos (Calcium Phosphate)"),
(" Bone injuries – trauma comes in","Calc Phos (Calcium Phosphate)"),
(" bones","Calc Flor (Calcium Floride) "),
(" Bones and ","Calc Flor (Calcium Floride) "),
(" Bones become inflamed after radiation treatments","Calc Phos (Calcium Phosphate)"),
(" both chronically and acutely","Calc Flor (Calcium Floride) "),
(" Brain fatigue – brain fag","Kali Phos (Potassium Phosphoricum)"),
(" breast cancer with a tendency to ulcer","Calc Flor (Calcium Floride) "),
(" breasts cysts","Silica (Silica)"),
(" Brings boils to a head","Silica (Silica)"),
(" Brittle matrix of the bones","Calc Phos (Calcium Phosphate)"),
(" brittle nails","Silica (Silica)"),
(" Bunions","Calc Flor (Calcium Floride) "),
(" Bunions","Silica (Silica)"),
(" Burning of the skin","Kali Sulph (Potassium Sulphate)"),
(" burny feeling without a bad breath","Ferrum Phos (Ferrum Phosphoricum)"),
(" business troubles","Kali Phos (Potassium Phosphoricum)"),
(" but she did and turned into a pillar of salt","Nat Mur (Natrum Muriaticum)"),
(" but sometimes better at the seaside will indicate it","Nat Mur (Natrum Muriaticum)"),
(" but there is no way to satisfy them","Calc Phos (Calcium Phosphate)"),
(" Calc Carb & Calc Phos are the 2 biggest constitutional remedies in homeopathy (Murphy) Calc Carb’s are stocky & Calc Phos is thin","Calc Phos (Calcium Phosphate)"),
(" Calc Carb is deeper than Ruta or Rhus Tox and Calc Flor is even deeper","Calc Flor (Calcium Floride) "),
(" Calc Carb is for the bones","Calc Sulph (Calcium Sulphate)"),
(" Calc Flor follows Ruta","Calc Flor (Calcium Floride) "),
(" calc flor is for the outside enamel","Calc Phos (Calcium Phosphate)"),
(" Calc Flor is good for the tendency to ulcer","Calc Flor (Calcium Floride) "),
(" Calc Flor is the chronic remedy","Mag Phos (Magnesium Phosphate)"),
(" Calc Flor is the chronic remedy for Ruta","Calc Flor (Calcium Floride) "),
(" Calc Flor is the indurated remedy – symptoms of induration are normally soft tissue that has become hardened","Calc Flor (Calcium Floride) "),
(" Calc Flor shares many of the same symptom qualities of the homeopathic remedy Ruta","Calc Flor (Calcium Floride) "),
(" Calc Flor strengthens the ligaments and tendons","Calc Flor (Calcium Floride) "),
(" Calc Flor will soften the tissues","Calc Flor (Calcium Floride) "),
(" Calc Phos – feels as if the legs are cold from the knees to the feet","Calc Phos (Calcium Phosphate)"),
(" Calc Phos are the top remedies","Calc Phos (Calcium Phosphate)"),
(" Calc Phos children can be obstinate","Calc Phos (Calcium Phosphate)"),
(" Calc Phos children can be precocious & intellectual","Calc Phos (Calcium Phosphate)"),
(" Calc Phos is an important remedy for growth and development","Calc Phos (Calcium Phosphate)"),
(" calc phos is for the inside structure of the teeth","Calc Phos (Calcium Phosphate)"),
(" Calc Phos is the best remedy to give during growth spurts","Calc Phos (Calcium Phosphate)"),
(" Calc phos is the top remedy to give to children when teething","Calc Phos (Calcium Phosphate)"),
(" Calc Phos patients do not know what they want","Calc Phos (Calcium Phosphate)"),
(" Calc Phos people are friendly and make friends easily","Calc Phos (Calcium Phosphate)"),
(" Calc Sulph is the 2nd remedy for acne","Calc Sulph (Calcium Sulphate)"),
(" calcification of the glands Skin: A good remedy for Carpenters","Calc Flor (Calcium Floride) "),
(" Calcium – earth",""),
(" callused hands","Calc Flor (Calcium Floride) "),
(" can’t live on a lake","Nat Sulph (Sodium Sulphate)"),
(" carbuncles (many boils) or furuncle (a single boil)","Calc Sulph (Calcium Sulphate)"),
(" Careworn look on the face","Kali Phos (Potassium Phosphoricum)"),
(" Carpenter’s – Nerve pain from using hands too much","Mag Phos (Magnesium Phosphate)"),
(" chicken pox","Ferrum Phos (Ferrum Phosphoricum)"),
(" Children after being vaccinated seem weaker","Silica (Silica)"),
(" Children and Parasites: Worms – a good remedy for children & babies and animals for worms","Nat Phos (Sodium Phosphate)"),
(" Children have a fever ","Calc Phos (Calcium Phosphate)"),
(" Children reject breast milk","Calc Phos (Calcium Phosphate)"),
(" Children: Silica children are very picky; when eating if 1 food touches another one they won’t eat it","Silica (Silica)"),
(" Chronic ear infections in children","Silica (Silica)"),
(" chronic fluid retention","Nat Mur (Natrum Muriaticum)"),
(" Chronic pain think of Nat Sulph and (Aurum)","Nat Sulph (Sodium Sulphate)"),
(" Chronic Problems: The underlying miasm for this remedy is TB; It is used when there is a tendency for colds and sore throats","Calc Phos (Calcium Phosphate)"),
(" Chronic remedy for Ignatia – A person really frustrated","Calc Phos (Calcium Phosphate)"),
(" Clear White mucous – congestion (kali bich) has an affinity for mucous Kali Mur & Ferrum Phos the top 2 tissue salts for colds","Kali Mur (Potassium Muriaticum) "),
(" clothes","Calc Flor (Calcium Floride) "),
(" colds and flu’s they lose their umph","Silica (Silica)"),
(" Colds begin with sneezing","Nat Mur (Natrum Muriaticum)"),
(" colic","Calc Phos (Calcium Phosphate)"),
(" Colic & Teething","Calc Phos (Calcium Phosphate)"),
(" Colitis","Mag Phos (Magnesium Phosphate)"),
(" Color",""),
(" Combines well with ginkgo","Kali Phos (Potassium Phosphoricum)"),
(" Computer Workers","Mag Phos (Magnesium Phosphate)"),
(" Confidence: Lack of self-confidence","Silica (Silica)"),
(" constipation Hives","Nat Mur (Natrum Muriaticum)"),
(" Contained in tooth enamel","Calc Flor (Calcium Floride) "),
(" contraction of joints","Calc Flor (Calcium Floride) "),
(" convalescent","Ferrum Phos (Ferrum Phosphoricum)"),
(" Corneal ulceration","Calc Flor (Calcium Floride) "),
(" coughs out yellow mucous","Nat Sulph (Sodium Sulphate)"),
(" Cracking nails","Silica (Silica)"),
(" Cracks in the feet in cold weather","Calc Sulph (Calcium Sulphate)"),
(" Cradle Cap in children","Calc Sulph (Calcium Sulphate)"),
(" Cramp in the neck with brachial neuralgia","Mag Phos (Magnesium Phosphate)"),
(" Cramps at night especially when sleeping","Mag Phos (Magnesium Phosphate)"),
(" Craves bacon and smoked meat such as salami – a calc phos keynote","Calc Phos (Calcium Phosphate)"),
(" Craves cigarettes – helps get rid of the craving for tobacco A very good remedy for menopause","Calc Phos (Calcium Phosphate)"),
(" crooked","Calc Flor (Calcium Floride) "),
(" Curvature of the spine","Calc Flor (Calcium Floride) "),
(" cuts and wounds that won’t heal","Calc Sulph (Calcium Sulphate)"),
(" Cystitis – Bladder infections especially from eating acidic foods or beverages","Nat Phos (Sodium Phosphate)"),
(" Dampness","Calc Flor (Calcium Floride) "),
(" Dampness: Nat Sulph – They can’t stand the dampness","Nat Sulph (Sodium Sulphate)"),
(" deafness","Kali Mur (Potassium Muriaticum) "),
(" Deafness due to calcium deposits in the ears – if the little bones don’t move (Thios)","Calc Flor (Calcium Floride) "),
(" Death of a loved one","Nat Mur (Natrum Muriaticum)"),
(" deep spinal ache’s < warm weather","Nat Sulph (Sodium Sulphate)"),
(" deformed","Calc Flor (Calcium Floride) "),
(" dehydration also see (Nat Mur) ","Nat Phos (Sodium Phosphate)"),
(" delicate skin","Silica (Silica)"),
(" delusion that going to fail","Silica (Silica)"),
(" demanding and sensitive – crabbiness","Calc Phos (Calcium Phosphate)"),
(" Dental abscesses and infections of the gums","Silica (Silica)"),
(" depressed and gloomy","Kali Phos (Potassium Phosphoricum)"),
(" depressed Toxic Liver","Nat Sulph (Sodium Sulphate)"),
(" Depression: In chronic pain cases","Nat Sulph (Sodium Sulphate)"),
(" Desire to put a hot","Mag Phos (Magnesium Phosphate)"),
(" Detoxification and Fasting: A great tissue salt to use for detoxification","Nat Phos (Sodium Phosphate)"),
(" Diarrhea in the morning after getting up","Nat Sulph (Sodium Sulphate)"),
(" diets high in uric acid such as the Atkin’s Diet","Nat Phos (Sodium Phosphate)"),
(" discharge like raw egg white","Nat Mur (Natrum Muriaticum)"),
(" Discontent","Calc Phos (Calcium Phosphate)"),
(" Dosage: 4 tablets under the tounge 3 – 4 X a day between meals","Calc Phos (Calcium Phosphate)"),
(" dowager’s hump","Calc Phos (Calcium Phosphate)"),
(" Drug addiction","Kali Phos (Potassium Phosphoricum)"),
(" drug overdose (Natum Arsenicosm #1 remedy for leukemia","Ferrum Phos (Ferrum Phosphoricum)"),
(" dry eczema especially in infants","Calc Sulph (Calcium Sulphate)"),
(" Dryness","Nat Mur (Natrum Muriaticum)"),
(" DT’s Senility","Kali Phos (Potassium Phosphoricum)"),
(" dwelling on the past","Nat Mur (Natrum Muriaticum)"),
(" Dysentery & Diarrhea NBWS (never have been well since)","Nat Phos (Sodium Phosphate)"),
(" Ear canal clogged","Kali Mur (Potassium Muriaticum) "),
(" earaches","Calc Phos (Calcium Phosphate)"),
(" Earaches","Ferrum Phos (Ferrum Phosphoricum)"),
(" Early stages of Pneumonia Conjunctivitis","Ferrum Phos (Ferrum Phosphoricum)"),
(" Ears – an abscess inside of the ear","Calc Sulph (Calcium Sulphate)"),
(" Ears: Ear infections with too much fluid","Kali Mur (Potassium Muriaticum) "),
(" easily frightened or startled","Kali Phos (Potassium Phosphoricum)"),
(" Emaciation about the neck","Nat Mur (Natrum Muriaticum)"),
(" Emotionally: It is the remedy for people who have suffered and want to help others","Nat Mur (Natrum Muriaticum)"),
(" Epilepsy 20 – 40% of epilepsy cases happened after a head injury","Nat Sulph (Sodium Sulphate)"),
(" especially in anemic persons","Ferrum Phos (Ferrum Phosphoricum)"),
(" especially of the ankles","Nat Phos (Sodium Phosphate)"),
(" especially thorasic and upper spine","Nat Sulph (Sodium Sulphate)"),
(" Even mild mental emotional symptoms of the above Nat Sulph","Nat Sulph (Sodium Sulphate)"),
(" Everyone goes to them for help","Nat Mur (Natrum Muriaticum)"),
(" Everything’s fine but tired","Ferrum Phos (Ferrum Phosphoricum)"),
(" exams","Kali Phos (Potassium Phosphoricum)"),
(" Excellent for the elderly and young children","Calc Flor (Calcium Floride) "),
(" Excema","Kali Sulph (Potassium Sulphate)"),
(" Eyes: Cataracts used at the early stages to help prevent and assist in dissolving them","Calc Flor (Calcium Floride) "),
(" Failure of the fontanels to close","Calc Phos (Calcium Phosphate)"),
(" failure to thrive","Calc Phos (Calcium Phosphate)"),
(" False Plethora","Ferrum Phos (Ferrum Phosphoricum)"),
(" famous blush remedy – false blush","Ferrum Phos (Ferrum Phosphoricum)"),
(" Famous Dandruff Remedy","Kali Sulph (Potassium Sulphate)"),
(" fatigue","Ferrum Phos (Ferrum Phosphoricum)"),
(" Fatigue – sluggishness of the whole system","Calc Phos (Calcium Phosphate)"),
(" Fear of public speaking","Silica (Silica)"),
(" Ferrum Metallicum is very close as a remedy","Ferrum Phos (Ferrum Phosphoricum)"),
(" Ferrum Phos is useful in inflammation of all tissues of the body except bone","Ferrum Phos (Ferrum Phosphoricum)"),
(" Fevers of unknown origin","Ferrum Phos (Ferrum Phosphoricum)"),
(" Fevers with weakness and exhaustion","Ferrum Phos (Ferrum Phosphoricum)"),
(" Fibrous tissues in the body – Silica firms up everything Silica is an important remedy for mineralization","Silica (Silica)"),
(" Fluid Balance – Too much –Too little fluid in the balance","Nat Mur (Natrum Muriaticum)"),
(" foot odor","Silica (Silica)"),
(" For complaining whining teenagers – they complain all the time","Calc Phos (Calcium Phosphate)"),
(" for people who can’t hear well after an ear infection","Kali Mur (Potassium Muriaticum) "),
(" frail body","Silica (Silica)"),
(" frustrated","Calc Phos (Calcium Phosphate)"),
(" frustrated easily","Calc Phos (Calcium Phosphate)"),
(" fussy","Calc Phos (Calcium Phosphate)"),
(" Genital Herpes","Nat Mur (Natrum Muriaticum)"),
(" Give Calc Phos to the mother to improve the quality of milk for breastfeeding","Calc Phos (Calcium Phosphate)"),
(" Give Calc Phos-at the end of every broken bone it’s used to facilitate healing and non-union of broken bones","Calc Phos (Calcium Phosphate)"),
(" Glands – Cancer of the glands","Calc Flor (Calcium Floride) "),
(" Glandular Problems: Enlarged tonsils","Calc Flor (Calcium Floride) "),
(" Glass","Silica (Silica)"),
(" going through the day is a burden","Kali Sulph (Potassium Sulphate)"),
(" Good for coffee drinkers to balance the acidity of the coffee","Nat Phos (Sodium Phosphate)"),
(" good for low hemoglobin in pregnancy","Ferrum Phos (Ferrum Phosphoricum)"),
(" gotu kola & lecithin (the phosphorus from lecithin is what’s used to make Kali Phos) Exam Funk","Kali Phos (Potassium Phosphoricum)"),
(" Gout - from too much uric acid","Nat Phos (Sodium Phosphate)"),
(" grains and proteins are acid forming","Nat Phos (Sodium Phosphate)"),
(" Great stress buster for students","Kali Phos (Potassium Phosphoricum)"),
(" green think –Nat Sulph NBWS Gonorrhea Asthma: Lungs – A big asthma remedy worse dampness","Nat Sulph (Sodium Sulphate)"),
(" Grief in children of divorced parents","Nat Mur (Natrum Muriaticum)"),
(" Growth and development: Slow growth and development in children","Calc Phos (Calcium Phosphate)"),
(" Growth problems #1 remedy for Growing Pains and bone pains","Calc Phos (Calcium Phosphate)"),
(" growth rates slow down","Silica (Silica)"),
(" hair","Calc Flor (Calcium Floride) "),
(" hair","Calc Sulph (Calcium Sulphate)"),
(" Hangover – Nat Phos (with Nux Vomica) Urinary and Female: A great kidney remedy – Kidney’s are a fluid balancing organ","Nat Phos (Sodium Phosphate)"),
(" Hayfever remedy with thin clear discharge and sneezing","Nat Mur (Natrum Muriaticum)"),
(" Head Injuries: *HEAD INJURIES – NBWS (never been well since) ","Nat Sulph (Sodium Sulphate)"),
(" Headaches – Like little hammer pounding away at the top of the head","Nat Mur (Natrum Muriaticum)"),
(" Headaches from exposure to the sun","Nat Mur (Natrum Muriaticum)"),
(" Headaches in school girls","Nat Mur (Natrum Muriaticum)"),
(" Heaviness","Nat Sulph (Sodium Sulphate)"),
(" heavy – headache with a scratchy sore throat","Ferrum Phos (Ferrum Phosphoricum)"),
(" heavy responsibilities; they take on all responsibilities of everyone around them","Nat Sulph (Sodium Sulphate)"),
(" Helps balance fluids moving in and out of cells","Nat Mur (Natrum Muriaticum)"),
(" Helps people on high protein diets","Nat Phos (Sodium Phosphate)"),
(" Helps people recover from infectious disease","Ferrum Phos (Ferrum Phosphoricum)"),
(" Helps prevent children from getting tubes in the ears","Kali Mur (Potassium Muriaticum) "),
(" Hematachlorosis – too many red blood cells Capillary fragility – bruise easily Bleeding hemorrhoids Blood in the urine with no symptoms","Ferrum Phos (Ferrum Phosphoricum)"),
(" hemorrhaging","Nat Phos (Sodium Phosphate)"),
(" Hemorrhoids and varicose veins","Calc Flor (Calcium Floride) "),
(" Hodgkin’s Disease Uterine Fibroids","Calc Flor (Calcium Floride) "),
(" HOT HOT to relieve the cramps","Mag Phos (Magnesium Phosphate)"),
(" hot water bottle on it","Mag Phos (Magnesium Phosphate)"),
(" humid weather","Nat Sulph (Sodium Sulphate)"),
(" Hypericum main whiplash remedies) #1 remedy – Ticks & Twitches of the Face","Mag Phos (Magnesium Phosphate)"),
(" hypersensitive to smoke","Calc Phos (Calcium Phosphate)"),
(" Hyperventilation Nightmares in children (wakes up screaming)","Kali Phos (Potassium Phosphoricum)"),
(" If Ruta doesn’t work then Calc Flor will aid the problem","Calc Flor (Calcium Floride) "),
(" In Nat Mur the wound is emotional – a wounded heart","Nat Mur (Natrum Muriaticum)"),
(" in northern climates when the snowmelts they feel stiff all over","Calc Phos (Calcium Phosphate)"),
(" Increased Thirst","Nat Mur (Natrum Muriaticum)"),
(" Increasing oxygenation a good remedy for runners and marathon runners","Ferrum Phos (Ferrum Phosphoricum)"),
(" Infants","Calc Phos (Calcium Phosphate)"),
(" Infants unable to tolerate even mother’s milk and will frequently vomit the milk","Silica (Silica)"),
(" Infants with difficulty holding up their head","Calc Phos (Calcium Phosphate)"),
(" Infection of tear duct or blocked tear duct of newborns","Silica (Silica)"),
(" Inflammation: The cardinal signs for inflammation are 1) Heat","Ferrum Phos (Ferrum Phosphoricum)"),
(" ingrown toenails","Silica (Silica)"),
(" Injuries to the spine","Calc Flor (Calcium Floride) "),
(" Inside vulnerable and sensitive","Nat Mur (Natrum Muriaticum)"),
(" Insomnia especially for people who work irregular hours","Kali Phos (Potassium Phosphoricum)"),
(" intestinal spasms","Mag Phos (Magnesium Phosphate)"),
(" Introverted – They love their books- Quiet type","Nat Mur (Natrum Muriaticum)"),
(" Irritable","Calc Phos (Calcium Phosphate)"),
(" irritable","Calc Phos (Calcium Phosphate)"),
(" irritable","Nat Sulph (Sodium Sulphate)"),
(" Irritable Bowel","Mag Phos (Magnesium Phosphate)"),
(" it can be used with Sepia","Calc Flor (Calcium Floride) "),
(" it has a very strong affinity for the wrist","Calc Flor (Calcium Floride) "),
(" It helps get minerals working again in the body","Silica (Silica)"),
(" It helps in the ability to assimilate foods easier","Calc Phos (Calcium Phosphate)"),
(" it helps the body with re-absorption of deeper boils","Calc Sulph (Calcium Sulphate)"),
(" it helps you get more out of your food","Calc Phos (Calcium Phosphate)"),
(" it is a good growth and development remedy for children in general","Calc Phos (Calcium Phosphate)"),
(" It is considered the chronic remedy of Ruta","Calc Flor (Calcium Floride) "),
(" It is the #1 remedy for Osteoporosis","Calc Phos (Calcium Phosphate)"),
(" It is the rescue remedy of the cell salts 1st stage of all acute diseases & it’s great for the end stage of disease","Ferrum Phos (Ferrum Phosphoricum)"),
(" it looks like pulsatilla but there is anemia","Ferrum Phos (Ferrum Phosphoricum)"),
(" It removes the tendency to adhesions after operations","Calc Flor (Calcium Floride) "),
(" It shares the modalities of Rhus Tox in that the affected part is better with movement","Calc Flor (Calcium Floride) "),
(" It was used in China to calm down nervous individuals","Calc Flor (Calcium Floride) "),
(" It’s a big remedy for ","Calc Flor (Calcium Floride) "),
(" It’s an excellent remedy to take with calcium supplements to enhance absorption of the supplement","Calc Phos (Calcium Phosphate)"),
(" it’s good for the tendency to get colds","Calc Phos (Calcium Phosphate)"),
(" It’s like Calc Sulph – but with thick yellow mucous from the lungs","Kali Sulph (Potassium Sulphate)"),
(" It’s the best of the 12 cell salt remedies for inflammation","Ferrum Phos (Ferrum Phosphoricum)"),
(" itching and burning after exertion","Nat Mur (Natrum Muriaticum)"),
(" joints and the muscle-skeletal system","Calc Flor (Calcium Floride) "),
(" Just when they get better they hear a song and go right back to their grief","Nat Mur (Natrum Muriaticum)"),
(" Kali Bromatum is the #1 remedy for acne","Calc Sulph (Calcium Sulphate)"),
(" Kali Mur for the runny nose","Kali Mur (Potassium Muriaticum) "),
(" Kali Phos is the mental stress cell salt","Calc Phos (Calcium Phosphate)"),
(" Kali Phos sharpens the memory","Kali Phos (Potassium Phosphoricum)"),
(" Kali Sulph – mimics Pulsatilla very close","Kali Sulph (Potassium Sulphate)"),
(" Kali Sulph is often the chronic remedy of Puls","Kali Sulph (Potassium Sulphate)"),
(" Kali Sulph people are very warm to hot","Kali Sulph (Potassium Sulphate)"),
(" Kali Sulph Pulsatilla Acrid Yellow mucous Bland yellow mucous Crave fresh air Crave fresh air Wandering pains Wandering pains Changeable moods Changeable moods Thirstless Thirstless < (worse) Heat < Sunset (better) Slow Motion > Slow Motion Rattling in the Lungs (Ant Tart is white & thick and rattling) Kali Sulph is yellow Asthma Several other asthma remedies: according to the time of the asthma attack Arsenicum 11PM – 1AM Kali Arsenicum 1:30 – 2:30AM Kali Carb 2AM – 4AM (arthritis","Kali Sulph (Potassium Sulphate)"),
(" Known for skin diseases especially with pus","Calc Sulph (Calcium Sulphate)"),
(" Lack of symptoms in childhood diseases","Ferrum Phos (Ferrum Phosphoricum)"),
(" learning disabilities Big head","Silica (Silica)"),
(" leaving pock marks","Silica (Silica)"),
(" Leg Cramps","Mag Phos (Magnesium Phosphate)"),
(" Leg Cramps in long distance runners","Mag Phos (Magnesium Phosphate)"),
(" Life is a struggle","Nat Sulph (Sodium Sulphate)"),
(" Like salt being rubbed in a wound","Nat Mur (Natrum Muriaticum)"),
(" like teeth enamel they want a job with a lot of prestige","Calc Flor (Calcium Floride) "),
(" liver problems","Nat Sulph (Sodium Sulphate)"),
(" Locked up and hardened tendon","Calc Flor (Calcium Floride) "),
(" look at the sun and start sneezing","Nat Mur (Natrum Muriaticum)"),
(" Loss of fluids – since bleeding","Nat Phos (Sodium Phosphate)"),
(" loss of vitality – think of Ferrum Phos","Ferrum Phos (Ferrum Phosphoricum)"),
(" Lots wife from the Bible – she wasn’t supposed to look back","Nat Mur (Natrum Muriaticum)"),
(" low birth weight","Calc Phos (Calcium Phosphate)"),
(" Low blood pressure – poor circulation","Ferrum Phos (Ferrum Phosphoricum)"),
(" Low blood sugar & hypoglycemic problems Skin: Hives","Nat Phos (Sodium Phosphate)"),
(" Low to midrange fevers","Ferrum Phos (Ferrum Phosphoricum)"),
(" lumpy cystic breast","Calc Flor (Calcium Floride) "),
(" Mag Phos can be put in warm water and sipped (no where else in homeopathy can this be found) ","Mag Phos (Magnesium Phosphate)"),
(" Major remedy for bad effects of vaccinations in newborns","Silica (Silica)"),
(" Mal-assimilation – Blood calcium is fine but the person is still showing symptoms of leg cramps and other problems","Calc Phos (Calcium Phosphate)"),
(" Man with chronic discharge from the urethra – yellow","Nat Sulph (Sodium Sulphate)"),
(" massage and heat","Calc Flor (Calcium Floride) "),
(" Massage Therapists","Calc Flor (Calcium Floride) "),
(" Mental and personality changes since spinal trauma","Nat Sulph (Sodium Sulphate)"),
(" Mental Emotional: Brittle mental and emotionally – they react easily to stress","Calc Phos (Calcium Phosphate)"),
(" Mental Emotional: Fear of poverty – people who are afraid to lose all their money","Calc Flor (Calcium Floride) "),
(" mental fatigue","Kali Phos (Potassium Phosphoricum)"),
(" mental occupations","Kali Phos (Potassium Phosphoricum)"),
(" mild fevers","Ferrum Phos (Ferrum Phosphoricum)"),
(" Milk may be an issue with Calc Phos","Calc Phos (Calcium Phosphate)"),
(" milky discharge White flaky danA1:V1druff","Kali Mur (Potassium Muriaticum) "),
(" mind","Silica (Silica)"),
(" moist sticky","Kali Sulph (Potassium Sulphate)"),
(" much worse from the sun","Nat Sulph (Sodium Sulphate)"),
(" Mucous can get thick white later on","Kali Mur (Potassium Muriaticum) "),
(" mucous clear to white but not sticky","Kali Mur (Potassium Muriaticum) "),
(" Mucous discharges that are yellow","Calc Sulph (Calcium Sulphate)"),
(" Must hold chest when coughing","Nat Sulph (Sodium Sulphate)"),
(" My grandmother can’t sleep since her husband died","Nat Mur (Natrum Muriaticum)"),
(" nails with white spots on them","Silica (Silica)"),
(" Nat Mur is one of the major remedies in homeopathic medicine It is considered a major grief remedy on the emotional level","Nat Mur (Natrum Muriaticum)"),
(" Nat Mur is useful in a wide variety of symptoms with opposite modalities","Nat Mur (Natrum Muriaticum)"),
(" Nat Mur people take everything with a grain of salt","Nat Mur (Natrum Muriaticum)"),
(" Nat Mur/Nat Phos work on the kidneys People who need diuretics","Nat Mur (Natrum Muriaticum)"),
(" Nat Phos taken with Kali Phos are good for fasting and detoxification Kali Phos calms you down and Nat Phos helps you eliminate toxins","Nat Phos (Sodium Phosphate)"),
(" Nat Sulph cannot live near water","Nat Sulph (Sodium Sulphate)"),
(" Nat Sulph is similar to arnica","Nat Sulph (Sodium Sulphate)"),
(" Nat-Mur people always feel worse by the sea","Nat Mur (Natrum Muriaticum)"),
(" Natrum Carb is a good remedy for children with a milk allergy","Calc Phos (Calcium Phosphate)"),
(" NBWS (never been well since) blood loss","Ferrum Phos (Ferrum Phosphoricum)"),
(" NBWS (Never been well since) Hepatitis","Nat Sulph (Sodium Sulphate)"),
(" Nerve Headaches – headaches over the eyes (pain over the eyebrow in the indentation it’s actually a neuralgia) Stomach cramps","Mag Phos (Magnesium Phosphate)"),
(" Neurasthenia – Nerve exhaustion","Kali Phos (Potassium Phosphoricum)"),
(" never crying in front of anyone","Nat Mur (Natrum Muriaticum)"),
(" No confidence in their ability to do the work","Silica (Silica)"),
(" Non-specific hemmhorage","Ferrum Phos (Ferrum Phosphoricum)"),
(" non-specific inflammation of the eardrum","Ferrum Phos (Ferrum Phosphoricum)"),
(" Nose – acrid thick yellow discharge Eyes: Conjunctivitis with discharge of thick yellow matter","Calc Sulph (Calcium Sulphate)"),
(" nose bleeding remedy #1 Phosphorus","Ferrum Phos (Ferrum Phosphoricum)"),
(" not breast-feeding","Calc Phos (Calcium Phosphate)"),
(" Oak Stiff Joints – the hands and feet swell easily Complaint of tiredness – Aversion to work","Kali Sulph (Potassium Sulphate)"),
(" On the physical level Nat Mur helps keep the balance of fluids working correctly","Nat Mur (Natrum Muriaticum)"),
(" One elbow is bigger than the other is","Calc Flor (Calcium Floride) "),
(" One of the main remedies used for the ringworm miasm it is often indicated for this condition","Calc Sulph (Calcium Sulphate)"),
(" Oppressed by the Heat & Humidity it protects people during the July","Nat Sulph (Sodium Sulphate)"),
(" or helps the body reabsorb them","Silica (Silica)"),
(" Or you find Nat Mur’s with the exact opposite who can’t take salt at all","Nat Mur (Natrum Muriaticum)"),
(" Osteogenesis imperfecta","Calc Phos (Calcium Phosphate)"),
(" osteomyleitis","Calc Phos (Calcium Phosphate)"),
(" Other: Neuromas – nerve tumors","Calc Flor (Calcium Floride) "),
(" pain in the eye and no other symptoms","Ferrum Phos (Ferrum Phosphoricum)"),
(" pain so severe that they temporarily loose their vision","Nat Mur (Natrum Muriaticum)"),
(" Painful teething","Calc Phos (Calcium Phosphate)"),
(" Painter’s from holding the brush Acute Carpal Tunnel Syndrome","Mag Phos (Magnesium Phosphate)"),
(" Parkinson’s disease","Mag Phos (Magnesium Phosphate)"),
(" People can be thin Acute exhaustion to get the stamina back Short energy expenditure range – Adults have 1 or 2 hours in the AM then exhausted","Silica (Silica)"),
(" People who dwell on the past","Nat Mur (Natrum Muriaticum)"),
(" People who manage their energy and time","Silica (Silica)"),
(" perfectionist","Calc Phos (Calcium Phosphate)"),
(" performance anxiety","Kali Phos (Potassium Phosphoricum)"),
(" Photophobia – Headaches from sunlight (#1 remedy is Natrum Carbonicum) Sun headaches after head injury","Nat Sulph (Sodium Sulphate)"),
(" physically","Kali Sulph (Potassium Sulphate)"),
(" Piano Player’s cramp","Mag Phos (Magnesium Phosphate)"),
(" picking of the nose","Nat Phos (Sodium Phosphate)"),
(" plantar’s warts","Nat Sulph (Sodium Sulphate)"),
(" Pregnancy & the Elderly","Calc Phos (Calcium Phosphate)"),
(" pre-mature","Calc Phos (Calcium Phosphate)"),
(" Pre-mature aging","Calc Phos (Calcium Phosphate)"),
(" present a shinny image to the world","Calc Flor (Calcium Floride) "),
(" pressure in the ear","Kali Mur (Potassium Muriaticum) "),
(" producing hard growths","Calc Flor (Calcium Floride) "),
(" Professionals who develop an aversion to their work – they feel incapable of performing their duties anymore","Silica (Silica)"),
(" Proper moisture balance","Nat Mur (Natrum Muriaticum)"),
(" prostration of mind","Kali Phos (Potassium Phosphoricum)"),
(" Pus under the scab – you pick it and find pus Cracked Hands - #1 remedy is Graphites especially behind the ears","Calc Sulph (Calcium Sulphate)"),
(" Quite organized and systematic","Calc Flor (Calcium Floride) "),
(" recurring – boils with a tendency to suppuration with yellow pus","Calc Sulph (Calcium Sulphate)"),
(" red throat","Ferrum Phos (Ferrum Phosphoricum)"),
(" responds well to Nat Mur","Nat Mur (Natrum Muriaticum)"),
(" Rest","Calc Flor (Calcium Floride) "),
(" restless","Kali Phos (Potassium Phosphoricum)"),
(" Rhus Tox","Mag Phos (Magnesium Phosphate)"),
(" Rickets – Vit D deficiency – osteomylasia","Calc Phos (Calcium Phosphate)"),
(" Ringworm & Ringworm of the scalp Leucorrehea – White discharge (Vaginitis) Yellow Stools","Kali Sulph (Potassium Sulphate)"),
(" rough cracked hands","Calc Flor (Calcium Floride) "),
(" rough hands","Calc Flor (Calcium Floride) "),
(" Rub Calc Phos tablets into the gums","Calc Phos (Calcium Phosphate)"),
(" Sacro illeac problems S","Calc Phos (Calcium Phosphate)"),
(" Satiated with life – Life is a burden","Nat Sulph (Sodium Sulphate)"),
(" Scaling – The skin dries off and falls off","Kali Sulph (Potassium Sulphate)"),
(" Sciatic Nerve (Kali Iodum is also good for Sciatica)  Better Massage  Pressure  Heat Right Sided Spasmodic Coughing – Whooping Cough Hicoughs – Spasm of the Diaphragm Colic in babies Toothaches > Hot drinks or heating pad on it (Chamomile is good for toothaches (homeopathic)) Severe pain in decayed teeth Shooting","Mag Phos (Magnesium Phosphate)"),
(" scoliosis in the elderly person (Silica first)","Calc Flor (Calcium Floride) "),
(" sensitive","Kali Phos (Potassium Phosphoricum)"),
(" Sensitive to sugar and sweets","Nat Phos (Sodium Phosphate)"),
(" sensitivity after eating pineapple or a lot of citrus or fruits","Calc Flor (Calcium Floride) "),
(" Severe back pains – severe sharp burning shooting pains","Calc Flor (Calcium Floride) "),
(" Shifting Pains Painful hand pains: Writer’s cramp","Mag Phos (Magnesium Phosphate)"),
(" Sighing (Ignatia) as if there isn’t enough oxygen and the person is compelled to take a deep breath that isn’t satisfying","Calc Phos (Calcium Phosphate)"),
(" Signs of this –A sour smell about the baby i","Calc Phos (Calcium Phosphate)"),
(" Silica also helps dogs and cats from problems with vaccinations","Silica (Silica)"),
(" silica develops fibromas","Silica (Silica)"),
(" Silica for the tendency to suppurate","Calc Flor (Calcium Floride) "),
(" Silica is a great energy manager; persons needing it delegate their energy","Silica (Silica)"),
(" Silica lacks grit – in the bones","Silica (Silica)"),
(" silica people sometim","Silica (Silica)"),
(" Silica’s have a fear of math","Silica (Silica)"),
(" Sinusitis","Kali Mur (Potassium Muriaticum) "),
(" Sinusitis with thick bland yellow mucous","Kali Sulph (Potassium Sulphate)"),
(" skin","Silica (Silica)"),
(" skin","Silica (Silica)"),
(" Skin dries out","Nat Mur (Natrum Muriaticum)"),
(" Skin that is unhealthy","Calc Sulph (Calcium Sulphate)"),
(" Sleepless from worry","Kali Phos (Potassium Phosphoricum)"),
(" Sodium and chloride ions are very important ions in extracellular fluid","Nat Mur (Natrum Muriaticum)"),
(" Sores","Calc Flor (Calcium Floride) "),
(" Sour smell coming of the baby or a person has a sour smell coming off their body","Nat Phos (Sodium Phosphate)"),
(" spinal osteoporosis","Calc Phos (Calcium Phosphate)"),
(" spine The skin is weak – every cut scars","Silica (Silica)"),
(" St John’s Wort & Kali Phos complimentary herbs go well with cell salts Kava with Kali Phos Chronic Fatigue syndrome from overuse of the brain","Kali Phos (Potassium Phosphoricum)"),
(" Stamina: Weakness","Silica (Silica)"),
(" Stocky Calc Carb","Calc Phos (Calcium Phosphate)"),
(" Stocky overweight persons with psoriasis","Calc Sulph (Calcium Sulphate)"),
(" stream or ocean","Nat Sulph (Sodium Sulphate)"),
(" Strengthens the hair","Silica (Silica)"),
(" Sulphur ",""),
(" surgery","Ferrum Phos (Ferrum Phosphoricum)"),
(" sweat eats through socks","Silica (Silica)"),
(" swelling of the hands and feet","Nat Mur (Natrum Muriaticum)"),
(" Swimmer’s ear","Kali Mur (Potassium Muriaticum) "),
(" Swimmer’s Ear – Painful (Kali Mur for the blockage) nerve pain","Mag Phos (Magnesium Phosphate)"),
(" swollen glands","Silica (Silica)"),
(" Talks in sleep Kali Phos is a convalecent remedy after stroke (arnica is very good if used immediately after a stroke) Worse worry","Kali Phos (Potassium Phosphoricum)"),
(" Tantrums – it could be worms or acid condition of the blood or kidneys Food and Digestion: Big appetite with little gain of weight – Nat Phos & Cina Food Allergies – serious food allergies Nat Phos can help the body deal with them","Nat Phos (Sodium Phosphate)"),
(" tears swell but don’t spill","Nat Mur (Natrum Muriaticum)"),
(" Teeth and Bones: 6X Calc Phos will regulate Calcium Metabolism","Calc Phos (Calcium Phosphate)"),
(" Teeth pain","Calc Phos (Calcium Phosphate)"),
(" Teeth that come in rotten","Calc Flor (Calcium Floride) "),
(" teething","Calc Phos (Calcium Phosphate)"),
(" Teething problems","Calc Phos (Calcium Phosphate)"),
(" Telephone workers from holding the neck crooked","Mag Phos (Magnesium Phosphate)"),
(" Tendencies to fungal infections like tinea","Calc Sulph (Calcium Sulphate)"),
(" Tendency to bruise easily","Calc Flor (Calcium Floride) "),
(" tendons and ligaments","Calc Flor (Calcium Floride) "),
(" The Anti-Spasmodic – Cramps & Spasms Anti-Spasmodic – Charlie Horses","Mag Phos (Magnesium Phosphate)"),
(" tooth coming in and the next tooth they don’t even feel after using Calc Phos in the interim period","Calc Phos (Calcium Phosphate)"),
(" The essence of the remedy is brittle bones","Calc Phos (Calcium Phosphate)"),
(" Ears won’t pop","Kali Mur (Potassium Muriaticum) "),
(" Fluids are off","Nat Mur (Natrum Muriaticum)"),
(" Very Hot Summer","Nat Sulph (Sodium Sulphate)"),
(" Lip cracks down the middle especially in the wintertime","Nat Mur (Natrum Muriaticum)"),
(" The main focus of this remedy is on the teeth","Calc Flor (Calcium Floride) "),
(" The major component of our bones","Calc Phos (Calcium Phosphate)"),
(" the matrix of the person is built around calcium","Calc Phos (Calcium Phosphate)"),
(" The mucosa in the vagina gets too acid","Nat Phos (Sodium Phosphate)"),
(" the mucous looks like uncooked or slightly soft-boiled egg white","Kali Mur (Potassium Muriaticum) "),
(" The person feels a little weak","Ferrum Phos (Ferrum Phosphoricum)"),
(" The remedy is often taken for periods of 3 to 6 months","Calc Flor (Calcium Floride) "),
(" the skin peels off; sometimes with a thick yellow discharge","Kali Sulph (Potassium Sulphate)"),
(" The stress cell salt","Calc Phos (Calcium Phosphate)"),
(" The tissues get too lax- the face sags","Calc Flor (Calcium Floride) "),
(" Then give the mother Calc Phos","Calc Phos (Calcium Phosphate)"),
(" There can be much itching which is worse at night","Kali Sulph (Potassium Sulphate)"),
(" They appear to be very strong but the eyes are very sensitive","Nat Mur (Natrum Muriaticum)"),
(" active physically as well as mentally and are very sensitive","Calc Phos (Calcium Phosphate)"),
(" afraid of losing their good looks and so go for face-lifts or older men will marry beautiful young wives to show off","Calc Flor (Calcium Floride) "),
(" fond of sports","Calc Phos (Calcium Phosphate)"),
(" very thirsty","Nat Mur (Natrum Muriaticum)"),
(" build a wall around them","Nat Mur (Natrum Muriaticum)"),
(" they buy a lot of insurance and stash money away in case of a financial recession","Calc Flor (Calcium Floride) "),
(" crave milk","Calc Phos (Calcium Phosphate)"),
(" intolerant of cold wet weather i","Calc Phos (Calcium Phosphate)"),
(" gain a few pounds of water weight","Nat Mur (Natrum Muriaticum)"),
(" Depression","Nat Mur (Natrum Muriaticum)"),
(" cry in bed by themselves","Nat Mur (Natrum Muriaticum)"),
(" don’t lack courage they lack the energy to do it","Silica (Silica)"),
(" don’t like to be consoled","Nat Mur (Natrum Muriaticum)"),
(" don’t want to show their grief","Nat Mur (Natrum Muriaticum)"),
(" feel tired and feverish and they don’t know what’s wrong","Ferrum Phos (Ferrum Phosphoricum)"),
(" they get respiratory problems","Silica (Silica)"),
(" They go to the bedroom and close the door so no one will see them cry","Nat Mur (Natrum Muriaticum)"),
(" weight loss – because of grief","Calc Phos (Calcium Phosphate)"),
(" they have no self-confidence because of their capabilities","Silica (Silica)"),
(" Ttendency to feel so over burdened","Nat Sulph (Sodium Sulphate)"),
(" Like to dwell on their misery","Nat Mur (Natrum Muriaticum)"),
(" Look healthy but they aren’t","Ferrum Phos (Ferrum Phosphoricum)"),
(" loss of confidence and they go into chronic depression","Nat Sulph (Sodium Sulphate)"),
(" love to travel","Calc Phos (Calcium Phosphate)"),
(" tend to get cold easily Use after surgery to help get strength back #1 cell salt for pre-mature babies Silica & Calc Phos Slowness in development","Silica (Silica)"),
(" Eyes irritated wear sunglasses","Nat Mur (Natrum Muriaticum)"),
(" Tire easily","Silica (Silica)"),
(" Confidence issues","Calc Flor (Calcium Floride) "),
(" Hard Laborious job","Calc Flor (Calcium Floride) "),
(" thick and lumpy","Calc Sulph (Calcium Sulphate)"),
(" Thin Calc Phos they grow too fast with not enough stability for the tissues","Calc Phos (Calcium Phosphate)"),
(" This gives us the essence of the whole remedy – The recreation of the bone isn’t happening","Calc Phos (Calcium Phosphate)"),
(" this is often the least used tissue salt","Calc Sulph (Calcium Sulphate)"),
(" This remedy along with calc phos can fix the metabolic problems in children","Calc Flor (Calcium Floride) "),
(" TMJ – numbness and tingling with a cold sensation in the jaw","Calc Phos (Calcium Phosphate)"),
(" toenail problems with fungus","Silica (Silica)"),
(" Tonsillitis a good sore throat remedy Other: They can have white spots on the nails","Calc Phos (Calcium Phosphate)"),
(" too little or too tight","Calc Flor (Calcium Floride) "),
(" too much dislocation","Calc Flor (Calcium Floride) "),
(" Too much salt","Nat Mur (Natrum Muriaticum)"),
(" Torn ligaments","Ferrum Phos (Ferrum Phosphoricum)"),
(" Trick knees – The knee gives out (Ruta)","Calc Flor (Calcium Floride) "),
(" Trigeminal Neuralgia ( Spigelia","Mag Phos (Magnesium Phosphate)"),
(" Urethra discharges that are yellow and thick","Calc Sulph (Calcium Sulphate)"),
(" Use after an ear infection","Kali Mur (Potassium Muriaticum) "),
(" Used for bedsores","Calc Flor (Calcium Floride) "),
(" uterine hemmhorage with bright red blood","Ferrum Phos (Ferrum Phosphoricum)"),
(" Vaginitis – thick yellow discharge that can be burning or excoriating","Calc Sulph (Calcium Sulphate)"),
(" Vaginitis – White thick or clear – like eggwhite","Kali Mur (Potassium Muriaticum) "),
(" Vaginitis from too much yeast or acid foods in the diet","Nat Phos (Sodium Phosphate)"),
(" Veins and elastic tissues: It tonifies the elastic tissues","Calc Flor (Calcium Floride) "),
(" wakes up with leg and foot cramps","Mag Phos (Magnesium Phosphate)"),
(" Warts on the genitalia or perianal region (thuja)","Nat Sulph (Sodium Sulphate)"),
(" Warts on the hands","Nat Sulph (Sodium Sulphate)"),
(" warts which are usually hard","Silica (Silica)"),
(" Water retention before menstrual cycle High Blood Pressure – Salt sensitive pressure problems sensitive to the Sun","Nat Mur (Natrum Muriaticum)"),
(" weak & fragile  I need more stamina Lack of heat","Silica (Silica)"),
(" weak and easily exhausted","Kali Phos (Potassium Phosphoricum)"),
(" Weak memory & overuse of the brain","Kali Phos (Potassium Phosphoricum)"),
(" weariness","Silica (Silica)"),
(" wet and stillness which aggravates the stiffness of the affected part","Calc Flor (Calcium Floride) "),
(" when all you have is redness","Ferrum Phos (Ferrum Phosphoricum)"),
(" When Calc Phos mothers get angry the breast milk tastes sour to the baby","Calc Phos (Calcium Phosphate)"),
(" when Ruta is used acutely Calc Flor finishes the repair work needed for the injured tendon or ligament","Calc Flor (Calcium Floride) "),
(" when you burn Pulsatilla the ash is very high in Potassium Sulphate this is why so similar","Kali Sulph (Potassium Sulphate)"),
(" with stinging in the evening","Nat Phos (Sodium Phosphate)"),
(" wood splinters – it will bring out the old splinter","Silica (Silica)"),
(" worse cold","Calc Flor (Calcium Floride) "),
(" worse exertion","Silica (Silica)"),
(" Worse from Sun: A gigantic remedy for headaches","Nat Sulph (Sodium Sulphate)"),
(" Worse: Change of weather","Calc Flor (Calcium Floride) "),
(" Yawning","Kali Phos (Potassium Phosphoricum)"),
(" Yellow coating at the back of the tongue","Nat Phos (Sodium Phosphate)"),
(" Yellow coating on the tongue","Nat Sulph (Sodium Sulphate)"),
(" Yellow coating on the tongue Yellow slimy tongue","Kali Sulph (Potassium Sulphate)"),
(" yellow dandruff","Kali Sulph (Potassium Sulphate)"),
(" Yellow Diarrhea","Kali Sulph (Potassium Sulphate)"),
(" yellow discharge coming out of the ear","Kali Sulph (Potassium Sulphate)"),
(" Yellow discharges A good residual remedy for children with bronchitis","Kali Sulph (Potassium Sulphate)"),
(" Yellow green sinusitis","Nat Sulph (Sodium Sulphate)"),
(" Yellow thick pus","Calc Sulph (Calcium Sulphate)"),
(" You can build people up with this remedy","Calc Phos (Calcium Phosphate)"),
("Back Problems: Calc Flor has and affinity for the lower back","Calc Flor (Calcium Floride) "),
("Bone Spurs (Hekla Lava)","Calc Flor (Calcium Floride) "),
("Bumps or bony growths","Calc Flor (Calcium Floride) "),
("Carpal Tunnel Syndrome","Calc Flor (Calcium Floride) "),
("degeneration of the vertebrae","Calc Flor (Calcium Floride) "),
("Disc problems","Calc Flor (Calcium Floride) "),
("Elastic tissue – too much or too little","Calc Flor (Calcium Floride) "),
("Ganglion cysts","Calc Flor (Calcium Floride) "),
("heat & brimstone - Earth & Fire Commonly known as gypsum or plaster of paris",""),
("herniated discs that keeps re herniating","Calc Flor (Calcium Floride) "),
("Injury of the wrist – it’s too loose","Calc Flor (Calcium Floride) "),
("Joints slip out of sockets easily – gentle continual pressure with the palm of the hand can pop a joint back in","Calc Flor (Calcium Floride) "),
("Joints: The #1cell salt remedy for ","Calc Flor (Calcium Floride) "),
("slipped disc","Calc Flor (Calcium Floride) "),
("Teeth: Strengthens the tooth enamel so it is helpful for children who get cavities easily","Calc Flor (Calcium Floride) "),
("Tendons and Ligaments: It’s a good remedy for people who can’t hold adjustments after chiropractic treatment","Calc Flor (Calcium Floride) "),
("Tendons that contract or you get tumors on the tendon","Calc Flor (Calcium Floride) "),
("Total personality change after a mild or severe concussion","Nat Sulph (Sodium Sulphate)"),
("trauma to the joints","Calc Flor (Calcium Floride) "),
("Cough coming with mucus "," Nat Mur (Natrum Muriaticum)"),
("Cough coming again and again "," Nat Mur (Natrum Muriaticum), Ferrum Phos (Ferrum Phosphoricum), Mag Phos (Magnesium Phosphate), Kali Mur (Potassium Muriaticum), Kali Phos (Potassium Phosphate)"),
("Pain-related "," Ferrum Phos (Ferrum Phosphoricum)"),
("Cough due to fever ","Calc Sulph (Calcium Sulfate)"),
("Old cough in cancer patients "," Calc Phos (Calcium Phosphate), Silicae, Nat Mur (Natrum Muriaticum)"),
("Pain in the left side of the abdomen while coughing "," Kali Phos (Potassium Phosphate)"),
("Tears flow from the eyes while coughing "," Nat Mur (Natrum Muriaticum)"),
("Chest pain while coughing "," Nat Mur (Natrum Muriaticum), Ferrum Phos (Ferrum Phosphoricum)"),
("Feeling of tightness in the chest while coughing "," Silicae"),
("Night sweats "," Silicae"),
("Cough becomes lighter "," Ferrum Phos (Ferrum Phosphoricum), Nat Mur (Natrum Muriaticum)"),
("Scratching behind the breastbone and cough due to it "," Nat Mur (Natrum Muriaticum), Kali Mur (Potassium Muriaticum)"),
("Scratching in the throat "," Calc Flor (Calcium Floride)"),
("Scratching at night "," Calc Flor (Calcium Floride)"),
("Scratching in the respiratory tract "," Ferrum Phos (Ferrum Phosphoricum), Kali Phos (Potassium Phosphate), Silicae"),
("Cough coming on its own "," Mag Phos (Magnesium Phosphate), Calc Flor (Calcium Floride), Silicae"),
("Tongue sticking out and stretching "," Calc Flor (Calcium Floride)"),
("While lying down "," Nat Mur (Natrum Muriaticum)"),
("More in warm room "," Kali Phos (Potassium Phosphate)"),
("More in the morning "," Kali Phos (Potassium Phosphate)"),
("More in the evening ","Kali Mur (Potassium Muriaticum)"),
("Feels good coughing on its own "," Calc Phos (Calcium Phosphate)"),
("Feels good after coughing "," Calc Phos (Calcium Phosphate)"),
("Feels good in open air "," Kali Phos (Potassium Phosphate)"),
("Need open air to feel better "," Kali Phos (Potassium Phosphate)"),
("Dry cough, shaking from the inside "," Ferrum Phos (Ferrum Phosphoricum), Nat Mur (Natrum Muriaticum)"),
("Mucus discharge while coughing "," Nat Mur (Natrum Muriaticum)"),
("Nausea while coughing and vomiting after "," Nat Mur (Natrum Muriaticum)"),
("Due to air in the room, swallowing something, physical exertion, walking, eating sour food, internal heat "," Nat Mur (Natrum Muriaticum)"),
("Due to drinking hot drinks "," Nat Mur (Natrum Muriaticum)"),
("Coming at night due to itching "," Kali Phos (Potassium Phosphate)"),
("Severe, mild, and recurring "," Ferrum Phos (Ferrum Phosphoricum), Kali Mur (Potassium Muriaticum) "),
("Old cough in patients whose hands and feet always get cold "," Calc Phos (Calcium Phosphate)"),
("Cough caused by bending the neck and touching the throat (glands) "," Ferrum Phos (Ferrum Phosphoricum)"),
("While sitting straight "," Nat Mur (Natrum Muriaticum)"),
("Forceful cough with running nose "," Kali Mur (Potassium Muriaticum)"),
]